// AUTO-GENERATED by scripts/genblur.cjs — do not edit by hand.
// Intrinsic image dimensions + format for next/image (regenerated on prebuild).
export type ImageMeta = { w: number; h: number; format?: string };
export const imageMeta: Record<string, ImageMeta> = {
  "/images/achievment-1.png": {
    "w": 1280,
    "h": 895,
    "format": "png"
  },
  "/images/achievment-2-ykt_heroes.png": {
    "w": 636,
    "h": 431,
    "format": "png"
  },
  "/images/achievment-3-diploma.jpeg": {
    "w": 3508,
    "h": 2480,
    "format": "jpeg"
  },
  "/images/achievment-4-drawing.jpg": {
    "w": 3264,
    "h": 2448,
    "format": "jpeg"
  },
  "/images/avatar-rectangular.jpg": {
    "w": 1000,
    "h": 976,
    "format": "jpeg"
  },
  "/images/avatar.png": {
    "w": 600,
    "h": 600,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-1.png": {
    "w": 2048,
    "h": 1152,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-2.png": {
    "w": 960,
    "h": 871,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-3.png": {
    "w": 720,
    "h": 2194,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-4.png": {
    "w": 2048,
    "h": 1152,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-5.png": {
    "w": 1903,
    "h": 935,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-6.png": {
    "w": 1920,
    "h": 1378,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-7.png": {
    "w": 1920,
    "h": 2389,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-8.png": {
    "w": 2048,
    "h": 1152,
    "format": "png"
  },
  "/images/cases/lofty-homepage/img-9.png": {
    "w": 1740,
    "h": 1710,
    "format": "png"
  },
  "/images/cases/vtb-push-onboarding/flow-comparison.png": {
    "w": 3840,
    "h": 2530,
    "format": "png"
  },
  "/images/cases/vtb-push-onboarding/img-1.png": {
    "w": 3840,
    "h": 2160,
    "format": "png"
  },
  "/images/cases/vtb-push-onboarding/img-2.png": {
    "w": 3840,
    "h": 2160,
    "format": "png"
  },
  "/images/cases/vtb-push-onboarding/img-3.png": {
    "w": 1920,
    "h": 1252,
    "format": "png"
  },
  "/images/cases/vtb-push-onboarding/img-4.png": {
    "w": 3840,
    "h": 2160,
    "format": "png"
  },
  "/images/cases/vtb-push-onboarding/previous-toggle-flow.png": {
    "w": 3840,
    "h": 1520,
    "format": "png"
  },
  "/images/cases/vtb-template-constructor/img-1.png": {
    "w": 2048,
    "h": 1213,
    "format": "png"
  },
  "/images/cases/vtb-template-constructor/img-2.png": {
    "w": 2048,
    "h": 1514,
    "format": "png"
  },
  "/images/cases/vtb-template-constructor/img-3.png": {
    "w": 2048,
    "h": 1435,
    "format": "png"
  },
  "/images/cases/vtb-template-constructor/img-4.png": {
    "w": 2048,
    "h": 1213,
    "format": "png"
  },
  "/images/cases/vtb-template-constructor/img-5.png": {
    "w": 2048,
    "h": 1213,
    "format": "png"
  },
  "/images/cases/vtb-template-constructor/img-6.png": {
    "w": 2048,
    "h": 1213,
    "format": "png"
  },
  "/images/cases/vtb-template-constructor/img-7.png": {
    "w": 1704,
    "h": 1450,
    "format": "png"
  },
  "/images/cases/vtb-template-constructor/vtb-admin-case-cover.png": {
    "w": 2884,
    "h": 1819,
    "format": "png"
  },
  "/images/cases/ykt-jobs/img-1.png": {
    "w": 1370,
    "h": 1827,
    "format": "png"
  },
  "/images/cases/ykt-jobs/img-2.png": {
    "w": 351,
    "h": 760,
    "format": "png"
  },
  "/images/cases/ykt-jobs/img-3.png": {
    "w": 351,
    "h": 760,
    "format": "png"
  },
  "/images/cases/ykt-jobs/img-4.png": {
    "w": 351,
    "h": 705,
    "format": "png"
  },
  "/images/cases/ykt-jobs/img-5.png": {
    "w": 1993,
    "h": 1120,
    "format": "png"
  },
  "/images/cases/ykt-jobs/img-6.png": {
    "w": 1995,
    "h": 1121,
    "format": "png"
  },
  "/images/cases/ykt-jobs/img-7.png": {
    "w": 1920,
    "h": 1100,
    "format": "png"
  },
  "/images/cases/ykt-jobs/img-8.png": {
    "w": 940,
    "h": 1851,
    "format": "png"
  },
  "/images/cases/ykt-pickup/edaykt-case-cover.png": {
    "w": 1920,
    "h": 1200,
    "format": "png"
  },
  "/images/cases/ykt-pickup/img-1.png": {
    "w": 2378,
    "h": 1664,
    "format": "png"
  },
  "/images/cases/ykt-pickup/img-2.png": {
    "w": 1750,
    "h": 1710,
    "format": "png"
  },
  "/images/cases/ykt-pickup/img-3.png": {
    "w": 2160,
    "h": 1416,
    "format": "png"
  },
  "/images/cases/ykt-pickup/img-4.png": {
    "w": 320,
    "h": 240,
    "format": "gif"
  },
  "/images/cases/ykt-pickup/img-5.png": {
    "w": 3390,
    "h": 2526,
    "format": "png"
  },
  "/images/cases/ykt-pickup/img-6.png": {
    "w": 3390,
    "h": 2526,
    "format": "png"
  },
  "/images/lofty-homepage.png": {
    "w": 2048,
    "h": 1152,
    "format": "png"
  },
  "/images/template-constructor.png": {
    "w": 2361,
    "h": 1398,
    "format": "png"
  },
  "/images/vtb-push-case-cover.png": {
    "w": 3840,
    "h": 2400,
    "format": "png"
  },
  "/images/wave.png": {
    "w": 256,
    "h": 256,
    "format": "png"
  },
  "/images/ykt-jobs.png": {
    "w": 3840,
    "h": 2400,
    "format": "png"
  }
};
