// Regenerates content/blur.ts (LQIP placeholders) and content/imageMeta.ts
// (intrinsic width/height/format) for next/image. Runs on "prebuild".
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const PROJECT = path.join(__dirname, "..");
const ROOT = path.join(PROJECT, "public", "images");
const BLUR_OUT = path.join(PROJECT, "content", "blur.ts");
const META_OUT = path.join(PROJECT, "content", "imageMeta.ts");

function collect(dir) {
  const files = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...collect(p));
    else if (/\.(png|jpe?g|webp|gif)$/i.test(e.name)) files.push(p);
  }
  return files;
}

const keyFor = (f) =>
  "/" + path.relative(PROJECT, f).split(path.sep).slice(1).join("/"); // drop "public"

(async () => {
  if (!fs.existsSync(ROOT)) {
    console.warn("genblur: no public/images dir, skipping");
    return;
  }
  const files = collect(ROOT).sort();
  const blur = {};
  const meta = {};
  for (const f of files) {
    const key = keyFor(f);
    const img = sharp(f);
    const m = await img.metadata();
    meta[key] = { w: m.width, h: m.height, format: m.format };
    const buf = await sharp(f)
      .resize(24, 24, { fit: "inside" })
      .jpeg({ quality: 35 })
      .toBuffer();
    blur[key] = "data:image/jpeg;base64," + buf.toString("base64");
  }

  fs.writeFileSync(
    BLUR_OUT,
    "// AUTO-GENERATED by scripts/genblur.cjs — do not edit by hand.\n" +
      "// Tiny LQIP blur placeholders for next/image (regenerated on prebuild).\n" +
      "export const blur: Record<string, string> = " +
      JSON.stringify(blur, null, 2) +
      ";\n"
  );
  fs.writeFileSync(
    META_OUT,
    "// AUTO-GENERATED by scripts/genblur.cjs — do not edit by hand.\n" +
      "// Intrinsic image dimensions + format for next/image (regenerated on prebuild).\n" +
      "export type ImageMeta = { w: number; h: number; format?: string };\n" +
      "export const imageMeta: Record<string, ImageMeta> = " +
      JSON.stringify(meta, null, 2) +
      ";\n"
  );
  console.log(
    `genblur: wrote ${Object.keys(blur).length} placeholders + meta to content/`
  );
})();
