// Regenerates content/blur.ts — tiny base64 LQIP blur placeholders for next/image.
// Runs automatically before every build via the "prebuild" npm script.
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..", "public", "images");
const OUT = path.join(__dirname, "..", "content", "blur.ts");

function collect(dir) {
  const files = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...collect(p));
    else if (/\.(png|jpe?g|webp)$/i.test(e.name)) files.push(p);
  }
  return files;
}

(async () => {
  if (!fs.existsSync(ROOT)) {
    console.warn("genblur: no public/images dir, skipping");
    return;
  }
  const files = collect(ROOT).sort();
  const out = {};
  for (const f of files) {
    const buf = await sharp(f)
      .resize(24, 24, { fit: "inside" })
      .jpeg({ quality: 35 })
      .toBuffer();
    const key = "/" + path.relative(path.join(__dirname, ".."), f)
      .split(path.sep)
      .slice(1) // drop "public"
      .join("/");
    out[key] = "data:image/jpeg;base64," + buf.toString("base64");
  }
  const body =
    "// AUTO-GENERATED by scripts/genblur.cjs — do not edit by hand.\n" +
    "// Tiny LQIP blur placeholders for next/image (regenerated on prebuild).\n" +
    "export const blur: Record<string, string> = " +
    JSON.stringify(out, null, 2) +
    ";\n";
  fs.writeFileSync(OUT, body);
  console.log(`genblur: wrote ${Object.keys(out).length} placeholders to content/blur.ts`);
})();
